### ISSUE TITLE
dpkg: error processing package open-as-cgw (--configure): MySQL Configuration... FAILED

### ISSUE THREAD

**Issue by siucdude** [open-as-team/open-as-cgw#37] opened 2016-08-08 23:26 UTC
*** Preparing MySQL Configuration... FAILED
dpkg: error processing package open-as-cgw (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 open-as-cgw
E: Sub-process /usr/bin/dpkg returned an error code (1)
Reading package lists...
Building dependency tree...
Reading state information...
open-as-cgw is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up open-as-cgw (2.1.0-0~146~ubuntu14.04.1) ...
*** Preparing System User Accounts... OK
*** Preparing Crypto Configuration... OK
*** Preparing Base System Configuration... OK
*** Preparing SSH Configuration... OK
*** Preparing Open AS Configuration... OK
*** Preparing CLI Configuration... OK
*** Preparing CRON Configuration... OK
*** Preparing Postfix Configuration... OK
*** Preparing PostFWD Configuration... OK
*** Preparing Spamassassin Configuration... OK
*** Preparing Clamd Antivirus... OK
*** Preparing MySQL Configuration... FAILED
dpkg: error processing package open-as-cgw (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 open-as-cgw
E: Sub-process /usr/bin/dpkg returned an error code (1)
-----------------------------------------------------------
OPEN AS Communication Gateway installation FAILED!
-----------------------------------------------------------
Please copy the console output and the dpkg and apt logs
located at /var/log and open a new ticket in our bugtracker
Thank you in advance!
-----------------------------------------------------------

**Comment by siucdude** [comment] 2016-08-08 23:28
[root@spam1:/var/log] $ tail dpkg.log 
2016-08-08 17:21:54 status installed syslog-ng-core:amd64 3.5.3-1
2016-08-08 17:24:45 startup packages configure
2016-08-08 17:24:45 configure open-as-cgw:all 2.1.0-0~146~ubuntu14.04.1 <none>
2016-08-08 17:24:45 status half-configured open-as-cgw:all 2.1.0-0~146~ubuntu14.04.1
2016-08-08 17:37:42 startup packages configure
2016-08-08 17:37:42 configure open-as-cgw:all 2.1.0-0~146~ubuntu14.04.1 <none>
2016-08-08 17:37:42 status half-configured open-as-cgw:all 2.1.0-0~146~ubuntu14.04.1
2016-08-08 17:37:56 startup packages configure
2016-08-08 17:37:56 configure open-as-cgw:all 2.1.0-0~146~ubuntu14.04.1 <none>
2016-08-08 17:37:56 status half-configured open-as-cgw:all 2.1.0-0~146~ubuntu14.04.1

[root@spam1:/var/log/apt] $ tailf term.log 
*** Preparing Postfix Configuration... OK
*** Preparing PostFWD Configuration... OK
*** Preparing Spamassassin Configuration... OK
*** Preparing Clamd Antivirus... OK
*** Preparing MySQL Configuration... FAILED
dpkg: error processing package open-as-cgw (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 open-as-cgw
Log ended: 2016-08-08  17:38:07
 ^C
[root@spam1:/var/log/apt] $ tail history.log 

Start-Date: 2016-08-08  17:37:42
Commandline: apt-get -y -q upgrade
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2016-08-08  17:37:54

Start-Date: 2016-08-08  17:37:56
Commandline: apt-get -q -y install open-as-cgw
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2016-08-08  17:38:07
[root@spam1:/var/log/apt] $ cd ..

**Comment by schallertd** [comment] 2016-08-08 23:41
Hello,

was there a MySQL or MariaDB already present on the particular box? I've just tested with a fresh Ubuntu 16.04 LTS and the installer went through without issues.

We aware of the fact that the installer script currently does not prompt for mysql credentials and therfor might fail if there is already an instance running with different credentials. See the mysql postinst routine in https://github.com/open-as-team/open-as-cgw/blob/master/debian/open-as-cgw.postinst#L291

Thanks

**Comment by schallertd** [comment] 2016-08-13 00:17
Unfortunately I was not able to reproduce this issue with a clean Ubuntu 16.04 LTS. There must have been a mysql-server installed prior to the installation of open-as-cgw, which resulted in wrong mysql root credentials end therefore failed our postinst script.

Since we just switched from MySQL to MariaDB, this issue should be resolved. MariaDB has a new plugin called unix_socket Authentication, which basically allows the root user (or sudo) always to access the mariadb instance.

See https://mariadb.com/kb/en/mariadb/unix_socket-authentication-plugin/

Closing this for now.

**Closed by schallertd** 2016-08-13 00:17 UTC
Labels: bug

**Comment by siucdude** [comment] 2016-08-16 13:06
Sorry I was working on a different issue recently could not respond, but here are the steps i took,

with 14.04.x (x=I tried 3 different versions) these are all clean install with nothing preinstalled but OpenSSH server, 

After install I tried the install and everytime the MySQL position skips and asks for password... cna't figure it out... its ok Im moving to 16.04 and will try to get that working.

Thanks
